(cl:defpackage arm_gazebo-msg
  (:use )
  (:export
   "<JOINTVALUES>"
   "JOINTVALUES"
   "<ROTATIONTRANSLATIONINPUT>"
   "ROTATIONTRANSLATIONINPUT"
   "<ROTATIONTRANSLATIONOUTPUT>"
   "ROTATIONTRANSLATIONOUTPUT"
  ))

