// Generated by gencpp from file arm_gazebo/RotationTranslationInput.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_ROTATIONTRANSLATIONINPUT_H
#define ARM_GAZEBO_MESSAGE_ROTATIONTRANSLATIONINPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct RotationTranslationInput_
{
  typedef RotationTranslationInput_<ContainerAllocator> Type;

  RotationTranslationInput_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gama(0.0)
    , d(0)  {
    }
  RotationTranslationInput_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gama(0.0)
    , d(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _alpha_type;
  _alpha_type alpha;

   typedef double _beta_type;
  _beta_type beta;

   typedef double _gama_type;
  _gama_type gama;

   typedef int64_t _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> const> ConstPtr;

}; // struct RotationTranslationInput_

typedef ::arm_gazebo::RotationTranslationInput_<std::allocator<void> > RotationTranslationInput;

typedef boost::shared_ptr< ::arm_gazebo::RotationTranslationInput > RotationTranslationInputPtr;
typedef boost::shared_ptr< ::arm_gazebo::RotationTranslationInput const> RotationTranslationInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator1> & lhs, const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.alpha == rhs.alpha &&
    lhs.beta == rhs.beta &&
    lhs.gama == rhs.gama &&
    lhs.d == rhs.d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator1> & lhs, const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbe30b78a86e6a76f83d6f916d1be6e8";
  }

  static const char* value(const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbe30b78a86e6a76ULL;
  static const uint64_t static_value2 = 0xf83d6f916d1be6e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/RotationTranslationInput";
  }

  static const char* value(const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"float64 alpha\n"
"float64 beta\n"
"float64 gama\n"
"\n"
"int64 d\n"
;
  }

  static const char* value(const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.alpha);
      stream.next(m.beta);
      stream.next(m.gama);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotationTranslationInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::RotationTranslationInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::RotationTranslationInput_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "alpha: ";
    Printer<double>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<double>::stream(s, indent + "  ", v.beta);
    s << indent << "gama: ";
    Printer<double>::stream(s, indent + "  ", v.gama);
    s << indent << "d: ";
    Printer<int64_t>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_ROTATIONTRANSLATIONINPUT_H
